export {default as NavBar} from './navBar/NavBar'
export {default as NavigationDots} from './NavigationDots'
export {default as SocialMedia} from './SocialMedia'
export {default as AnimatedBackground} from './animatedBackground'
export * from './terminal'
